### PR TITLE
Fix going to homepage if file doesn't exist

### PR DESCRIPTION
**Pull request by rbunce**

### CODE REVIEW

**Comment by rbunce** [comment]
@richardfullmer think this is what should fix it if going to image.overnightprints.com base url tries to load homepage instead of 404ing, but then again will this cause all the things no in file storage table to 404 lol?

**Comment by rbunce** [comment]
@richardfullmer yeah testing local, everything not in file storage 404s, so your broken code was a feature so it worked sort of lol, need advise how to handle this please.

**Comment by rbunce** [comment]
@richardfullmer like need to detect if route exists for request or not before 404ing

**Comment by richardfullmer** [comment]
Good catch.  Thanks

**Pull request merged**
